// src/themes/themes.js

export const themes = {
  codeman: {
    name: "codeman",
    fonts: {
      heading: "'JetBrains Mono', monospace",
      body: "'Inter', sans-serif",
      prose: "'Lora', serif", // ← bio / long-form text
      mono: "'JetBrains Mono', monospace",
      googleFonts:
        "https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;700&family=Inter:wght@400;500&family=Lora:ital,wght@0,400;0,500;1,400&display=swap",
    },
    colors: {
      sidebarBg: "#0f0f0f",
      sidebarText: "#555",
      sidebarActive: "#68E0CF",
      sidebarBorder: "#1e1e1e",
      sidebarLogo: "#68E0CF",
      contentBg: "#141414",
      contentText: "#d4d4d0",
      contentMuted: "#555",
      contentBorder: "#272727",
      accent: "#68E0CF",
      accentDark: "#0F6E56",
      accentBg: "rgba(104,224,207,0.08)",
      topbarBg: "#0f0f0f",
      topbarText: "#68E0CF",
      bottomNavBg: "#0f0f0f",
      bottomNavBorder: "#1e1e1e",
      cardBg: "#1a1a1a",
      cardBorder: "#272727",
      cardBorderHover: "#68E0CF",
      badgeBg: "#1a2e28",
      badgeText: "#68E0CF",
    },
    layout: {
      type: "split",
      sidebarWidth: "220px",
      sidebarIconWidth: "52px",
    },
  },

  terminal: {
    name: "terminal",
    fonts: {
      heading: "'Fira Code', monospace",
      body: "'Fira Code', monospace",
      prose: "'Fira Code', monospace",
      mono: "'Fira Code', monospace",
      googleFonts:
        "https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;500;700&display=swap",
    },
    colors: {
      sidebarBg: "#0d0d0d",
      sidebarText: "#4a4a4a",
      sidebarActive: "#39ff14",
      sidebarBorder: "#1a1a1a",
      sidebarLogo: "#39ff14",
      contentBg: "#111111",
      contentText: "#c8c8c8",
      contentMuted: "#555",
      contentBorder: "#222",
      accent: "#39ff14",
      accentDark: "#1a7a00",
      accentBg: "rgba(57,255,20,0.07)",
      topbarBg: "#0d0d0d",
      topbarText: "#39ff14",
      bottomNavBg: "#0d0d0d",
      bottomNavBorder: "#1a1a1a",
      cardBg: "#161616",
      cardBorder: "#222",
      cardBorderHover: "#39ff14",
      badgeBg: "#0a1f0a",
      badgeText: "#39ff14",
    },
    layout: {
      type: "split",
      sidebarWidth: "220px",
      sidebarIconWidth: "48px",
    },
  },

  minimal: {
    name: "minimal",
    fonts: {
      heading: "'DM Serif Display', serif",
      body: "'DM Sans', sans-serif",
      prose: "'DM Sans', sans-serif",
      mono: "'DM Mono', monospace",
      googleFonts:
        "https://fonts.googleapis.com/css2?family=DM+Serif+Display&family=DM+Sans:wght@400;500&family=DM+Mono:wght@400;500&display=swap",
    },
    colors: {
      sidebarBg: "transparent",
      sidebarText: "#888",
      sidebarActive: "#1a1a1a",
      sidebarBorder: "#e5e5e5",
      sidebarLogo: "#1a1a1a",
      contentBg: "#ffffff",
      contentText: "#1a1a1a",
      contentMuted: "#999",
      contentBorder: "#ebebeb",
      accent: "#1a1a1a",
      accentDark: "#1a1a1a",
      accentBg: "#f5f5f5",
      topbarBg: "#ffffff",
      topbarText: "#1a1a1a",
      bottomNavBg: "#ffffff",
      bottomNavBorder: "#ebebeb",
      cardBg: "#fafafa",
      cardBorder: "#ebebeb",
      cardBorderHover: "#1a1a1a",
      badgeBg: "#f0f0f0",
      badgeText: "#444",
    },
    layout: {
      type: "single",
      sidebarWidth: "0px",
      sidebarIconWidth: "0px",
    },
  },
};
